version: "3.8"
services:
  backend:
    image: "cactitlr/springboot-react-fullstack:8.4.2022.12.0.27"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev